### ISSUE TITLE
No profile picture set looks weird

### ISSUE THREAD

**Issue by QC-Scooter** [canvasplus/extension#32] opened 2021-11-04 18:42 UTC
There's a bug for my teachers/students who don't have a profile picture set in dark & dim. Normally, Canvas gives them a picture made of 2 initials. The first letter of their first and last name. However, in dim/dark mode, it shows up as a very faint, gray circle. I managed to catch a slow frame for a second and saw that the normal picture showed up with the dark background and custom sidebar. But apparently another asset must've loaded in and replaced it.

**Comment by J-The-Dev** [comment] 2021-11-10 00:06
Is this what you were talking about?
It seems to be caused by `background: var(--cpt-dark-background-color) !important;` overwriting the background image.
![image](https://user-images.githubusercontent.com/83322224/141025246-aeee6d6a-29b2-415f-a341-dfc926fca2bb.png)

**Comment by QC-Scooter** [comment] 2021-11-10 00:48
Yep

**Comment by J-The-Dev** [comment] 2022-03-21 01:26
This should be fixed now

**Closed by J-The-Dev** 2022-03-21 01:26 UTC
Labels: bug
