### ISSUE TITLE
Causing High CPU Utilization Again

### ISSUE THREAD

**Issue by FieldPickle** [canvasplus/extension#52] opened 2022-09-11 02:54 UTC
Hello, I’m back because I'm experiencing the issue I spoke about in my previous issue report, which is now closed. **New Notes are In Bold.**

Any loaded Canvas page use 30-**85**+ % of CPU. **Have seen it cause 100% CPU utilization and made chrome freeze but not go unresponsive**

**Dashboard in particular, causes worse issues than other pages. And having multiple dashboard tabs exacerbates the issue, especially if in a separate window**

After loading noticed that my computer was chugging and investigated to find that chrome>canvas page was responsible. Confirmed was extension related by disabling and re-enabling one by one and narrowed down to Canvas plus **one of my all-time favorite extensions**. :(

**Reloaded page after each step: Closed all other chrome users and other browsers, disabled all other extensions other than Extensity(does not have page access and shows in chrome task manager separately), Tried to toggle individual settings of the extension**

Have attempted to relaunch chrome to no avail.

My Specs **(OLD)**)
CPU: Intel i7-10750H (running @4.2GHz)
RAM: 16GB 2933 Mhz
GPU1: Integrated
GPU2: 2070 max-Q

**My Specs (NEW):
Windows: 11 Pro 22H2
CPU: Intel i7-10750H (running @4.2GHz)
RAM: 16GB 2933 Mhz
GPU1: Integrated-(disabled in bios, using 2070 only through laptop MUX switch)
GPU2: 2070 max-Q
Displays: 4 total (1-1080p 144hz |2-1080p 144hz |3-1080p 170hz |4-1080p 25hz touch+pen)**

**_Screen Shots with Task Managers (Process Hacker shows unutilized CPU resources as "System Idle Process") - Edit_**

**1 Tab Dashboard:
 
![image](https://user-images.githubusercontent.com/104335335/189510261-3da0aded-d130-4033-be48-6020e565c8ca.png)

(0.4.4) kdkadcnebmokaadholinmnpjelphnghh // Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 // Installation Info: {"from":"install","timestamp":1650851862179} Survey Seed (1): 0.48828869456892465

2 Tabs Dashboard:
 
![image](https://user-images.githubusercontent.com/104335335/189510274-88ebb716-72be-411e-a354-19ce395fcb3c.png)

2 Tabs Dashboard(separate windows):

![image](https://user-images.githubusercontent.com/104335335/189510268-52c5d61e-c244-43d6-a96a-15981396ce74.png)

1 Tab Course Home:
 
![image](https://user-images.githubusercontent.com/104335335/189510279-82199a25-775e-4f04-b1be-1bd7a3fd6abd.png)

1 Tab Dashboard (Canvas+ disabled):

![image](https://user-images.githubusercontent.com/104335335/189510289-eb79a52d-9d25-43fe-a203-31ec95355a98.png)

1 Tab Dashboard (Canvas+ setting: Appearance Default):
 
![image](https://user-images.githubusercontent.com/104335335/189510299-8d1d3dcf-8b08-45fe-9863-8187f8ac2c1b.png)

1 Tab Dashboard (Canvas+ setting: most off):
 
![image](https://user-images.githubusercontent.com/104335335/189510308-3d96806b-9663-4e39-8f3a-5631939611f1.png)

DBUG : (0.4.4) kdkadcnebmokaadholinmnpjelphnghh // Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 // Installation Info: {"from":"install","timestamp":1650851862179} Survey Seed (1): 0.48828869456892465**

**Comment by FieldPickle** [comment] 2022-09-11 03:17
I figure it might be something as simple as a function or module looping excessively (i.e. if-else), running unchecked, or something like that.

**Comment by adriancasares** [comment] 2022-09-17 18:20
Hi, sorry for the long wait (out of town) – This issue should be fixed once google publishes the change. I'll close this once that goes through. Thank you for bringing this to my attention, turned out this was caused by one missing parameter 😳

**Closed** 2022-09-25 14:49 UTC
